#!/usr/bin/env python3
"""
Sentrada crossword layout engine.

Generates a British-style crossword from a company's answer/clue candidates and
renders a print-ready A2 puzzle page onto a blank cream template, with real,
perfect text every time.

    python crossword.py --template "Blank crossword template 25mb - upscaled.jpg" \
        --data test_cognism.json --output cognism_crossword.png

Sibling of the newspaper engine (../newspaper/newspaper.py): same Pango/Cairo text
layout, the same multiply-blend compositing so the paper texture shows through the
ink, the same resolution-independent zones (every position is a fraction of the
template dimensions, so one config works at any DPI), the same fontconfig font
registration, sRGB ICC tagging and print-production flags.

The template carries only the cream paper and the warm dark-brown double-rule
border. Everything inside it (title, subtitle, the crossword grid, the separator
rule, the Across/Down clue columns and the Sentrada credit) is drawn fresh each
run. The grid itself is generated by grid_generator.py from the candidate pool,
so its shape changes with every company.
"""

import argparse
import ctypes
import io
import json
import os
import sys

import grid_generator

# ---------------------------------------------------------------------------
# Register the bundled ../fonts directory with fontconfig BEFORE Pango is used,
# so the engine is self contained (mirrors the newspaper engine).
# ---------------------------------------------------------------------------

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
FONT_DIR = os.environ.get(
    "SENTRADA_FONT_DIR", os.path.normpath(os.path.join(SCRIPT_DIR, "..", "fonts"))
)


def register_app_fonts(font_dir):
    if not os.path.isdir(font_dir):
        print(f"[warn] font directory not found: {font_dir} (relying on system fonts)")
        return
    try:
        fc = ctypes.CDLL("libfontconfig.so.1")
    except OSError:
        try:
            fc = ctypes.CDLL("libfontconfig.so")
        except OSError:
            print("[warn] libfontconfig not loadable; relying on system fonts")
            return
    fc.FcConfigGetCurrent.restype = ctypes.c_void_p
    fc.FcConfigAppFontAddDir.argtypes = [ctypes.c_void_p, ctypes.c_char_p]
    fc.FcConfigAppFontAddDir.restype = ctypes.c_int
    if not fc.FcConfigAppFontAddDir(fc.FcConfigGetCurrent(), font_dir.encode("utf-8")):
        print(f"[warn] could not register app fonts from {font_dir}")


register_app_fonts(FONT_DIR)

import gi  # noqa: E402

gi.require_version("Pango", "1.0")
gi.require_version("PangoCairo", "1.0")
from gi.repository import GLib, Pango, PangoCairo  # noqa: E402

import cairo  # noqa: E402
from PIL import Image, ImageChops, ImageCms, ImageDraw, ImageFilter  # noqa: E402

# The production template is a deliberately high-resolution, trusted asset
# (the upscaled A2 blank is well over Pillow's default decompression-bomb
# guard of ~89M pixels). Lift the guard so loading it neither warns nor fails.
Image.MAX_IMAGE_PIXELS = None

SCALE = Pango.SCALE

# ---------------------------------------------------------------------------
# CONFIG. Everything that controls the look of the page. Zone rectangles are
# fractions of the image, origin top left, measured from the reference page.
# ---------------------------------------------------------------------------

CONFIG = {
    # Colours -----------------------------------------------------------------
    "ink": (0x3A / 255, 0x2E / 255, 0x22 / 255),       # warm dark brown, #3A2E22
    "grid_border": (0x1A / 255, 0x1A / 255, 0x1A / 255),  # near black, #1A1A1A
    "cell_fill": (0xFD / 255, 0xFB / 255, 0xF6 / 255),  # warm near-white cell
    # Fonts -------------------------------------------------------------------
    "font_title": "Playfair Display Bold",
    "font_subtitle": "Lora",
    "font_clue_head": "Playfair Display Bold",   # ACROSS / DOWN, spaced caps
    "font_clue_num": "Lora Bold",
    "font_clue_text": "Lora",
    "font_grid_num": "Lora Bold",
    "font_credit": "Lora Italic",
    # Content margins (fractions of width). The separator rule and the clue
    # columns live inside these; the title is centred on the page and may run a
    # little wider.
    "margin_x": 0.105,
    "right_x": 0.895,
    # Title -------------------------------------------------------------------
    "title_top": 0.062,          # top of the title cap line
    "title_w_frac": 0.82,        # title is sized to span up to this much width...
    "title_h_max": 0.046,        # ...and up to this much height (ink cap height)
    "title_tracking": 0.012,     # letterspacing as a fraction of title size
    "title_subtitle_gap": 0.018, # title baseline -> subtitle
    "size_subtitle": 0.0150,     # subtitle size, fraction of height
    "size_subtitle_min": 0.0105, # shrink floor: below this the subtitle check FAILs
    "subtitle_max_lines": 2,     # a long subtitle may wrap to at most this many lines
    # Grid --------------------------------------------------------------------
    "grid_top": 0.168,           # reserved grid rectangle, top (clear of the subtitle)...
    "grid_bottom": 0.648,        # ...and bottom (centre the square grid within). The
    # band is deliberately tall so the grid block reads as the A2 hero rather than
    # floating small with wide dead margins.
    "grid_w_frac": 0.74,         # grid may use up to this much page width
    "grid_border_frac": 0.030,   # cell border weight as a fraction of cell size
    "grid_num_frac": 0.30,       # cell-number size as a fraction of cell size
    "grid_num_pad_frac": 0.07,   # number inset from the cell's top-left corner
    # Separator + clues -------------------------------------------------------
    "grid_sep_gap": 0.034,       # grid bottom -> separator rule
    "sep_clue_gap": 0.026,       # separator rule -> ACROSS / DOWN headers
    "clue_bottom": 0.930,        # clues must end above this (credit sits below)
    "col_gap": 0.040,            # gap between the two clue columns
    "clue_head_tracking": 0.15,  # ACROSS / DOWN letterspacing (spaced small caps)
    "size_clue_head": 0.0130,    # ACROSS / DOWN header size, fraction of height
    "clue_head_gap": 0.018,      # header baseline -> first clue
    "clue_size_min": 0.0080,     # clue text auto-size range, fraction of height
    "clue_size_max": 0.0165,
    "clue_lead": 1.15,           # clue line leading (multiple of size)
    "clue_gap_frac": 0.50,       # gap between clues as a multiple of clue size
    "clue_num_gap_frac": 0.45,   # gap after the clue number, multiple of size
    # Credit ------------------------------------------------------------------
    "credit_text": "sentrada",
    "size_credit": 0.0135,
    "credit_bottom": 0.949,      # the credit's BOTTOM sits here, clear of the border
    # Separator rule weight (fraction of height) and colour matched to the ink.
    "sep_weight_frac": 0.0010,
    # Ink / paper realism (mirrors the newspaper engine). A faint sub-pixel blur
    # simulates ink spreading into the paper; scaled with resolution, capped low.
    "text_blur_px": 0.4,
    "blur_reference_width": 1055,
    "ink_blur_cap": 0.6,
    # Physical page size, for downsampling a supersampled render to print res.
    "a2_mm": (420, 594),         # A2 portrait
    # Print production (off by default; see the newspaper engine for the rationale).
    "crop_mark_mm": 4.0,
    "crop_mark_weight_mm": 0.12,
    "crop_mark_gap_mm": 1.5,
    # Grid generation defaults (overridable per data file / CLI).
    "min_words": 15,
    "max_words": 20,
    "grid_attempts": 500,
}

# ---------------------------------------------------------------------------
# Pango helpers (same idiom as the newspaper engine).
# ---------------------------------------------------------------------------


def _whole_range(attr, text):
    attr.start_index = 0
    attr.end_index = len(text.encode("utf-8"))
    return attr


def make_layout(cr):
    return PangoCairo.create_layout(cr)


def set_font(layout, font_str, size_px):
    fd = Pango.FontDescription.from_string(font_str)
    fd.set_absolute_size(size_px * SCALE)
    layout.set_font_description(fd)


def build_attrs(text, *, leading_px=None, letter_spacing_px=None):
    attrs = Pango.AttrList()
    if leading_px is not None:
        attrs.insert(_whole_range(
            Pango.attr_line_height_new_absolute(int(round(leading_px * SCALE))), text))
    if letter_spacing_px is not None:
        attrs.insert(_whole_range(
            Pango.attr_letter_spacing_new(int(round(letter_spacing_px * SCALE))), text))
    return attrs


def draw_layout(cr, layout, x, y, ink):
    cr.save()
    cr.set_source_rgb(*ink)
    cr.move_to(x, y)
    PangoCairo.show_layout(cr, layout)
    cr.restore()


def measure(layout):
    return layout.get_pixel_size()


def max_line_width(layout):
    """Widest single line in a (possibly wrapped) layout, in px. Used to verify a
    centred, width-constrained layout actually fits its box on every line."""
    widest = 0
    for i in range(layout.get_line_count()):
        _ink, logical = layout.get_line_readonly(i).get_pixel_extents()
        widest = max(widest, logical.width)
    return widest


def largest_fitting(feasible, lo, hi, iters=34):
    """Largest value in [lo, hi] for which feasible(value) is True, assuming
    feasible is monotone. Used to size text to fill a zone without overflowing."""
    if not feasible(lo):
        return lo, False
    if feasible(hi):
        return hi, True
    for _ in range(iters):
        mid = (lo + hi) / 2.0
        if feasible(mid):
            lo = mid
        else:
            hi = mid
    return lo, True


def smarten(text):
    """Typographic apostrophes/quotes and an ellipsis, plus the house style rule
    that em dashes become a comma break (mirrors the newspaper engine)."""
    if text is None:
        return ""
    text = str(text)
    for ch in ("—", "―", "‒", "⸺", "⸻"):
        text = text.replace(" " + ch + " ", ", ").replace(ch, ", ")
    text = text.replace(" -- ", ", ").replace("--", ", ").replace("...", "…")
    out, opener = [], " \t\n([{‘“"
    for i, ch in enumerate(text):
        prev = text[i - 1] if i > 0 else ""
        if ch == '"':
            out.append("“" if (prev == "" or prev in opener) else "”")
        elif ch == "'":
            nxt = text[i + 1] if i + 1 < len(text) else ""
            out.append("‘" if ((prev == "" or prev in opener) and not nxt.isdigit()) else "’")
        else:
            out.append(ch)
    return "".join(out)


# ---------------------------------------------------------------------------
# Element renderers. Each stashes any geometry the next element chains off in ctx.
# ---------------------------------------------------------------------------


def render_title(cr, ctx, data):
    """Title in bold premium serif, centred, auto-sized to span the available
    width (and capped on height), then the subtitle centred beneath it."""
    W, H, cfg, ink = ctx["W"], ctx["H"], ctx["cfg"], ctx["cfg"]["ink"]
    company = (data.get("company_name") or "").strip()
    title = smarten(data.get("title") or f"THE {company} CROSSWORD").upper()

    avail_w = cfg["title_w_frac"] * W
    cap_h = cfg["title_h_max"] * H
    layout = make_layout(cr)

    def ink_extents(size):
        set_font(layout, cfg["font_title"], size)
        layout.set_attributes(build_attrs(title, letter_spacing_px=cfg["title_tracking"] * size))
        layout.set_text(title, -1)
        return layout.get_pixel_extents()[0]

    def feasible(size):
        r = ink_extents(size)
        return r.width <= avail_w and r.height <= cap_h

    size, fits = largest_fitting(feasible, 0.020 * H, 0.075 * H)
    r = ink_extents(size)
    ctx["title_fit"] = {"fits": bool(fits) and r.width <= avail_w,
                        "over_px": max(0.0, r.width - avail_w)}
    title_top = cfg["title_top"] * H
    # Centre on the page; offset by the ink rect so the caps sit optically centred.
    x = (W - r.width) / 2.0 - r.x
    y = title_top - r.y
    draw_layout(cr, layout, x, y, ink)
    title_bottom = title_top + r.height

    # Subtitle, centred beneath the title, FIT to the content width the same way
    # the title fits to width: try the configured size, wrap to at most
    # subtitle_max_lines, and shrink the font until it fits. A constrained,
    # centre-aligned layout (with char-level wrap as a last resort) means a long
    # subtitle can never shear off the page margins the way an unconstrained
    # single line did. The pre-render check (run_checks) FAILs if it still cannot
    # fit at the minimum size, rather than shipping a clipped piece.
    subtitle = smarten(data.get("subtitle") or "How well do you know your own company?")
    content_w = (1.0 - 2.0 * cfg["margin_x"]) * W
    max_lines = cfg["subtitle_max_lines"]
    sl = make_layout(cr)
    sl.set_width(int(round(content_w * SCALE)))
    sl.set_alignment(Pango.Alignment.CENTER)
    sl.set_wrap(Pango.WrapMode.WORD_CHAR)   # break a word only as a last resort; never clip

    def lay_subtitle(size):
        set_font(sl, cfg["font_subtitle"], size)
        sl.set_text(subtitle, -1)
        return sl.get_line_count(), max_line_width(sl)

    def fits_at(size):
        lines, widest = lay_subtitle(size)
        return lines <= max_lines and widest <= content_w + 1.0

    size, _ = largest_fitting(fits_at, cfg["size_subtitle_min"] * H, cfg["size_subtitle"] * H)
    n_lines, widest = lay_subtitle(size)        # re-lay at the chosen size
    sw, sh = measure(sl)
    sy = title_bottom + cfg["title_subtitle_gap"] * H
    # The box is content_w wide with centre alignment, so draw at the content-box
    # left edge and let Pango centre each line within it.
    draw_layout(cr, sl, (W - content_w) / 2.0, sy, ink)
    header_bottom = sy + sh
    ctx["header_bottom"] = header_bottom

    # Hand the fit result to run_checks: too long to fit in max_lines at the
    # minimum size, or a wrapped subtitle that intrudes into the grid reserve.
    grid_top = cfg["grid_top"] * H
    ctx["subtitle_fit"] = {
        "fits": n_lines <= max_lines and widest <= content_w + 1.0
                and header_bottom <= grid_top + 1.0,
        "lines": n_lines,
        "max_lines": max_lines,
        "overflow_px": max(0.0, widest - content_w),
        "collides_grid": header_bottom > grid_top + 1.0,
        # Fit succeeded but deviated from the configured design: surfaced as a
        # WARN so the operator knows the piece wrapped or shrank without having
        # to spot it in the render.
        "shrunk_to": size / H if size < cfg["size_subtitle"] * H - 0.5 else None,
    }


def compute_grid_geometry(ctx, gridres):
    """Square-cell geometry for the generated grid, centred horizontally on the
    page and within the reserved vertical band. Returns (cell, ox, oy)."""
    W, H, cfg = ctx["W"], ctx["H"], ctx["cfg"]
    rows, cols = gridres["rows"], gridres["cols"]
    zone_top = cfg["grid_top"] * H
    zone_h = cfg["grid_bottom"] * H - zone_top
    zone_w = cfg["grid_w_frac"] * W
    cell = min(zone_w / max(1, cols), zone_h / max(1, rows))
    grid_w, grid_h = cell * cols, cell * rows
    ox = (W - grid_w) / 2.0                       # centred on the page width
    oy = zone_top + (zone_h - grid_h) / 2.0       # centred in the reserved band
    return cell, ox, oy


def render_grid(grid_cr, ctx, gridres):
    """Draw the British-style grid on its OWN surface: warm-white cell fills with
    near-black borders, and small bold numbers in the top-left of each light's
    start cell. Only lettered cells are drawn; the paper shows through the gaps.
    Drawn on a separate surface because the white fills must sit ON TOP of the
    paper (the ink text is multiplied INTO the paper), not be multiplied away."""
    cfg = ctx["cfg"]
    rows, cols, grid = gridres["rows"], gridres["cols"], gridres["grid"]
    numbers = gridres["numbers"]
    cell, ox, oy = ctx["cell"], ctx["grid_ox"], ctx["grid_oy"]
    border = max(1.0, cfg["grid_border_frac"] * cell)

    # 1) White cell fills.
    grid_cr.set_source_rgba(*cfg["cell_fill"], 1.0)
    for r in range(rows):
        for c in range(cols):
            if grid[r][c] is not None:
                grid_cr.rectangle(ox + c * cell, oy + r * cell, cell, cell)
                grid_cr.fill()

    # 2) Cell borders. Drawn as a set of UNIQUE edges (in grid-line coordinates)
    #    so an edge shared by two filled cells is struck exactly once. Stroking
    #    each cell rectangle instead double-strikes interior edges, making them
    #    read bolder than the outer ones.
    grid_cr.set_source_rgba(*cfg["grid_border"], 1.0)
    grid_cr.set_line_width(border)
    grid_cr.set_line_cap(cairo.LINE_CAP_SQUARE)
    edges = set()
    for r in range(rows):
        for c in range(cols):
            if grid[r][c] is None:
                continue
            edges.add(((c, r), (c + 1, r)))            # top
            edges.add(((c, r + 1), (c + 1, r + 1)))    # bottom
            edges.add(((c, r), (c, r + 1)))            # left
            edges.add(((c + 1, r), (c + 1, r + 1)))    # right
    for (a, b) in edges:
        grid_cr.move_to(ox + a[0] * cell, oy + a[1] * cell)
        grid_cr.line_to(ox + b[0] * cell, oy + b[1] * cell)
        grid_cr.stroke()

    # 3) Clue numbers, small and bold, inset into each start cell's top-left.
    pad = cfg["grid_num_pad_frac"] * cell
    num_size = cfg["grid_num_frac"] * cell
    for key, num in numbers.items():
        r, c = (int(v) for v in key.split(","))
        nl = make_layout(grid_cr)
        set_font(nl, cfg["font_grid_num"], num_size)
        nl.set_text(str(num), -1)
        draw_layout(grid_cr, nl, ox + c * cell + pad, oy + r * cell + pad * 0.4,
                    cfg["grid_border"])

    ctx["grid_bottom_px"] = oy + rows * cell


def render_clues(cr, ctx, gridres):
    """Two clue columns below the separator rule: ACROSS (left) and DOWN (right),
    headers in spaced caps, numbers bold and text regular weight, all auto-sized
    so the taller column fits the available depth. Returns nothing; draws the
    separator rule position into ctx for the post-composite pass."""
    W, H, cfg, ink = ctx["W"], ctx["H"], ctx["cfg"], ctx["cfg"]["ink"]
    mx, rx = cfg["margin_x"] * W, cfg["right_x"] * W

    # Separator rule sits a set gap below the grid, spanning the content width.
    sep_y = ctx["grid_bottom_px"] + cfg["grid_sep_gap"] * H
    ctx["separator"] = (mx, rx, sep_y)

    head_y = sep_y + cfg["sep_clue_gap"] * H
    clue_bottom = cfg["clue_bottom"] * H

    col_gap = cfg["col_gap"] * W
    col_w = (rx - mx - col_gap) / 2.0
    col_x = [mx, mx + col_w + col_gap]
    across = [smarten_entry(e) for e in gridres["across"]]
    down = [smarten_entry(e) for e in gridres["down"]]

    # Header layouts (ACROSS / DOWN) in spaced caps; fixed size relative to the
    # clue size band so they read as section heads.
    head_size = cfg["size_clue_head"] * H

    def header_layout(text):
        hl = make_layout(cr)
        set_font(hl, cfg["font_clue_head"], head_size)
        hl.set_attributes(build_attrs(text.upper(),
                                      letter_spacing_px=cfg["clue_head_tracking"] * head_size))
        hl.set_text(text.upper(), -1)
        return hl

    ah, dh = header_layout("ACROSS"), header_layout("DOWN")
    head_h = max(measure(ah)[1], measure(dh)[1])
    clue_top = head_y + head_h + cfg["clue_head_gap"] * H
    avail_h = clue_bottom - clue_top

    def number_layout(num, size):
        nl = make_layout(cr)
        set_font(nl, cfg["font_clue_num"], size)
        nl.set_attributes(build_attrs(str(num), leading_px=cfg["clue_lead"] * size))
        nl.set_text(str(num), -1)
        return nl

    def text_layout(clue, size, text_w):
        tl = make_layout(cr)
        set_font(tl, cfg["font_clue_text"], size)
        tl.set_width(int(text_w * SCALE))
        tl.set_wrap(Pango.WrapMode.WORD)
        tl.set_attributes(build_attrs(clue, leading_px=cfg["clue_lead"] * size))
        tl.set_text(clue, -1)
        return tl

    def hang_for(entries, size):
        # Hanging indent = widest number in the column + a gap, so every clue's
        # text aligns to one edge regardless of one- vs two-digit numbers.
        widest = max(measure(number_layout(e["number"], size))[0] for e in entries) if entries else 0
        return widest + cfg["clue_num_gap_frac"] * size

    def column_height(entries, size):
        if not entries:
            return 0.0
        hang = hang_for(entries, size)
        text_w = col_w - hang
        gap = cfg["clue_gap_frac"] * size
        total = sum(measure(text_layout(e["clue"], size, text_w))[1] + gap for e in entries)
        return max(0.0, total - gap)

    def feasible(size):
        return (column_height(across, size) <= avail_h
                and column_height(down, size) <= avail_h)

    size, fits = largest_fitting(feasible, cfg["clue_size_min"] * H, cfg["clue_size_max"] * H)
    ctx["clues_fit"] = fits

    # Draw headers, then the clues beneath each: bold number at the column edge,
    # regular text hung to a common indent (top-aligned, shared leading).
    draw_layout(cr, ah, col_x[0], head_y, ink)
    draw_layout(cr, dh, col_x[1], head_y, ink)

    for ci, entries in ((0, across), (1, down)):
        if not entries:
            ctx[f"clue_foot_{ci}"] = clue_top
            continue
        hang = hang_for(entries, size)
        text_w = col_w - hang
        gap = cfg["clue_gap_frac"] * size
        y = clue_top
        for e in entries:
            tl = text_layout(e["clue"], size, text_w)
            nl = number_layout(e["number"], size)
            draw_layout(cr, nl, col_x[ci], y, ink)
            draw_layout(cr, tl, col_x[ci] + hang, y, ink)
            y += measure(tl)[1] + gap
        ctx[f"clue_foot_{ci}"] = y - gap


def smarten_entry(entry):
    e = dict(entry)
    e["clue"] = smarten(entry["clue"])
    return e


def render_credit(cr, ctx, data):
    """Lowercase 'sentrada' credit, small and discreet, in the bottom-right
    corner just inside the content margin."""
    W, H, cfg, ink = ctx["W"], ctx["H"], ctx["cfg"], ctx["cfg"]["ink"]
    text = cfg["credit_text"]
    cl = make_layout(cr)
    set_font(cl, cfg["font_credit"], cfg["size_credit"] * H)
    cl.set_text(text, -1)
    cw, ch = measure(cl)
    x = cfg["right_x"] * W - cw
    y = cfg["credit_bottom"] * H - ch     # anchor the BOTTOM so it clears the border
    draw_layout(cr, cl, x, y, ink)


# ---------------------------------------------------------------------------
# Compositing (mirrors the newspaper engine).
# ---------------------------------------------------------------------------


def cairo_to_pil(surface):
    surface.flush()
    buf = io.BytesIO()
    surface.write_to_png(buf)
    buf.seek(0)
    return Image.open(buf).convert("RGBA")


def composite_ink(template_rgb, text_rgba, cfg, W, ink_blur=None):
    """Multiply the ink layer into the paper so the texture shows through."""
    if ink_blur is None:
        blur = min(cfg["ink_blur_cap"], cfg["text_blur_px"] * (W / float(cfg["blur_reference_width"])))
    else:
        blur = ink_blur
    if blur > 0:
        text_rgba = text_rgba.filter(ImageFilter.GaussianBlur(blur))
    white = Image.new("RGBA", template_rgb.size, (255, 255, 255, 255))
    ink_map = Image.alpha_composite(white, text_rgba).convert("RGB")
    return ImageChops.multiply(template_rgb, ink_map)


def draw_separator(image_rgb, ctx):
    cfg = ctx["cfg"]
    x0, x1, y = ctx["separator"]
    colour = tuple(int(round(c * 255)) for c in cfg["ink"])
    w = max(1, int(round(cfg["sep_weight_frac"] * ctx["H"])))
    d = ImageDraw.Draw(image_rgb)
    d.line([(int(round(x0)), int(round(y))), (int(round(x1)), int(round(y)))], fill=colour, width=w)
    return image_rgb


# ---------------------------------------------------------------------------
# Output finishing (downsample to print DPI, sRGB tag, bleed + crop marks).
# Same behaviour as the newspaper engine.
# ---------------------------------------------------------------------------


def finalize_output(result, cfg, print_dpi, print_size):
    if print_size:
        tw, th = print_size
    elif print_dpi:
        mm = cfg["a2_mm"]
        tw = int(round(mm[0] / 25.4 * print_dpi))
        th = int(round(mm[1] / 25.4 * print_dpi))
    else:
        return result, None
    src_ar, dst_ar = result.width / result.height, tw / th
    if abs(src_ar - dst_ar) > 0.01:
        print(f"[warn] template aspect ratio {src_ar:.4f} differs from the print "
              f"target {dst_ar:.4f}; the downsample will distort slightly.")
    if (tw, th) != result.size:
        print(f"[info] downsampling {result.width}x{result.height} -> {tw}x{th} for print"
              + (f" at {print_dpi} DPI" if print_dpi else ""))
        result = result.resize((tw, th), Image.LANCZOS)
    return result, print_dpi


_SRGB_ICC = None


def srgb_icc_bytes():
    # Header datetime + profile ID zeroed: LittleCMS stamps generation time,
    # which would make byte-identical re-renders impossible.
    global _SRGB_ICC
    if _SRGB_ICC is None:
        raw = bytearray(ImageCms.ImageCmsProfile(ImageCms.createProfile("sRGB")).tobytes())
        raw[24:36] = bytes(12)
        raw[84:100] = bytes(16)
        _SRGB_ICC = bytes(raw)
    return _SRGB_ICC


def effective_dpi(image, cfg):
    return image.width / (cfg["a2_mm"][0] / 25.4)


def add_bleed_and_marks(image, cfg, bleed_mm, crop_marks):
    if bleed_mm <= 0 and not crop_marks:
        return image
    dpi = effective_dpi(image, cfg)
    W, H = image.size
    bleed = max(0, int(round(bleed_mm / 25.4 * dpi)))
    if crop_marks:
        L = max(2, int(round(cfg["crop_mark_mm"] / 25.4 * dpi)))
        w = max(1, int(round(cfg["crop_mark_weight_mm"] / 25.4 * dpi)))
        gap = max(bleed, int(round(cfg["crop_mark_gap_mm"] / 25.4 * dpi)))
        pad = max(2, int(round(1.0 / 25.4 * dpi)))
        margin = gap + L + pad
    else:
        margin = bleed
    canvas = Image.new("RGB", (W + 2 * margin, H + 2 * margin), (255, 255, 255))
    canvas.paste(image, (margin, margin))
    if bleed > 0:
        top = image.crop((0, 0, W, 1)).resize((W, bleed))
        bot = image.crop((0, H - 1, W, H)).resize((W, bleed))
        left = image.crop((0, 0, 1, H)).resize((bleed, H))
        right = image.crop((W - 1, 0, W, H)).resize((bleed, H))
        canvas.paste(top, (margin, margin - bleed)); canvas.paste(bot, (margin, margin + H))
        canvas.paste(left, (margin - bleed, margin)); canvas.paste(right, (margin + W, margin))
        for cx, cy, sx, sy in ((margin - bleed, margin - bleed, 0, 0),
                               (margin + W, margin - bleed, W - 1, 0),
                               (margin - bleed, margin + H, 0, H - 1),
                               (margin + W, margin + H, W - 1, H - 1)):
            canvas.paste(image.crop((sx, sy, sx + 1, sy + 1)).resize((bleed, bleed)), (cx, cy))
    if crop_marks:
        d = ImageDraw.Draw(canvas)
        x0, y0, x1, y1 = margin, margin, margin + W, margin + H
        for tx, ty, hx, vy in ((x0, y0, -1, -1), (x1, y0, 1, -1), (x0, y1, -1, 1), (x1, y1, 1, 1)):
            d.line([(tx + hx * gap, ty), (tx + hx * (gap + L), ty)], fill=(0, 0, 0), width=w)
            d.line([(tx, ty + vy * gap), (tx, ty + vy * (gap + L))], fill=(0, 0, 0), width=w)
    return canvas


def assert_fonts_resolved(cr, cfg):
    """Hard-fail if any configured font family resolves to a substitute, so a
    fresh container missing the bundled ../fonts never silently renders in a
    fallback face (mirrors the newspaper engine's guard)."""
    layout = PangoCairo.create_layout(cr)
    pctx = layout.get_context()
    keys = ("font_title", "font_subtitle", "font_clue_head", "font_clue_num",
            "font_clue_text", "font_grid_num", "font_credit")
    checked, missing = set(), []
    for spec in (cfg[k] for k in keys):
        fd = Pango.FontDescription.from_string(spec)
        fam = (fd.get_family() or "").strip()
        if not fam or fam in checked:
            continue
        checked.add(fam)
        font = pctx.load_font(fd)
        resolved = (font.describe().get_family() if font else "") or ""
        if fam.lower() not in resolved.lower():
            missing.append((spec, f"resolved to '{resolved}'" if resolved else "no font loaded"))
    if missing:
        print("[error] required fonts did not resolve to their real faces:")
        for spec, why in missing:
            print(f"[error]   '{spec}' -> {why}")
        print(f"[error] check the bundled fonts in {FONT_DIR} (or set SENTRADA_FONT_DIR).")
        sys.exit(1)


# ---------------------------------------------------------------------------
# Checks.
# ---------------------------------------------------------------------------


def _derive_runs(grid, rows, cols):
    """Re-derive the across and down runs purely from the final grid geometry: a
    maximal sequence of >=2 filled cells starting where the previous cell (along
    the axis) is empty or off-grid. Returns two dicts keyed by start cell:
    {(r, c): "LETTERS"} for across and for down. This is the independent source of
    truth the solvability check compares the placed answers against."""
    across, down = {}, {}
    for r in range(rows):
        for c in range(cols):
            if grid[r][c] is None:
                continue
            if (c == 0 or grid[r][c - 1] is None) and c + 1 < cols and grid[r][c + 1] is not None:
                cc, letters = c, []
                while cc < cols and grid[r][cc] is not None:
                    letters.append(grid[r][cc]); cc += 1
                across[(r, c)] = "".join(letters)
            if (r == 0 or grid[r - 1][c] is None) and r + 1 < rows and grid[r + 1][c] is not None:
                rr, letters = r, []
                while rr < rows and grid[rr][c] is not None:
                    letters.append(grid[rr][c]); rr += 1
                down[(r, c)] = "".join(letters)
    return across, down


def verify_solvability(gridres):
    """Assert the puzzle is actually solvable: every numbered run in the grid
    geometry matches a placed answer (length and letters), there are no orphan
    runs or unchecked letters, and clue numbers and grid runs are in bijection.
    grid_generator places by real intersection so this holds by construction, but
    nothing else asserts it: a future change to placement or numbering could
    otherwise quietly ship a grid that breaks in the recipient's hands. All
    findings are FAILs so --check exits non-zero and the runner halts before
    render. Returns a list of (level, field, message)."""
    out = []
    grid, rows, cols = gridres["grid"], gridres["rows"], gridres["cols"]
    d_across, d_down = _derive_runs(grid, rows, cols)
    derived = {("across",) + k: w for k, w in d_across.items()}
    derived.update({("down",) + k: w for k, w in d_down.items()})

    placed = {}
    for e in gridres["across"]:
        placed[("across", e["row"], e["col"])] = e["answer"]
    for e in gridres["down"]:
        placed[("down", e["row"], e["col"])] = e["answer"]

    # 1) Every placed answer must have a grid run of the same length and letters.
    for (dirn, r, c), ans in placed.items():
        run = derived.get((dirn, r, c))
        if run is None:
            out.append(("fail", "grid", f"{dirn} answer '{ans}' at {r},{c} has no grid run"))
        elif run != ans:
            out.append(("fail", "grid",
                        f"{dirn} run at {r},{c} reads '{run}' but the clue answer is "
                        f"'{ans}' (length/letter mismatch: crossings do not resolve)"))

    # 2) No orphan runs: every >=2-cell run must be a real (clued) answer.
    numbered = {tuple(int(v) for v in k.split(",")) for k in gridres["numbers"]}
    for (dirn, r, c), run in derived.items():
        if (dirn, r, c) not in placed:
            out.append(("fail", "grid",
                        f"orphan {dirn} run '{run}' at {r},{c} has no clue (unchecked entry)"))
        if (r, c) not in numbered:
            out.append(("fail", "grid", f"{dirn} run at {r},{c} is not numbered"))

    # 3) No unchecked/orphan letters: every filled cell belongs to >=1 entry, so
    #    there are no stray 1-cell lights or letters reachable from no clue.
    covered = set()
    for (dirn, r, c), run in derived.items():
        for i in range(len(run)):
            covered.add((r, c + i) if dirn == "across" else (r + i, c))
    for r in range(rows):
        for c in range(cols):
            if grid[r][c] is not None and (r, c) not in covered:
                out.append(("fail", "grid",
                            f"cell {r},{c} ('{grid[r][c]}') belongs to no across or down "
                            f"entry (orphan letter)"))
    return out


def run_checks(ctx, gridres, cfg):
    out = []
    add = lambda lvl, field, msg: out.append((lvl, field, msg))
    if gridres.get("short"):
        add("warn", "grid", f"placed only {gridres['word_count']} words, below min_words")
    if gridres["word_count"] < 3:
        add("fail", "grid", "fewer than 3 words placed; not a viable crossword")
    # Solvability: the one place a bespoke crossword can quietly break.
    for lvl, field, msg in verify_solvability(gridres):
        add(lvl, field, msg)
    # Designated heroes that could not be anchored into the grid.
    for a in (gridres.get("anchors_missing") or []):
        add("fail", "anchor", f"designated anchor '{a}' could not be placed in the grid")
    tf = ctx.get("title_fit")
    if tf and not tf["fits"]:
        add("fail", "title",
            f"title does not fit the content width even at the minimum size "
            f"({tf['over_px']:.0f}px over) — it would overprint the border rules; "
            "shorten the title or company name")
    for a in (gridres.get("digit_dropped") or []):
        add("warn", "candidates",
            f"answer '{a}' contains digits and cannot render in the grid; "
            "dropped from the pool (its clue is unused)")
    sf = ctx.get("subtitle_fit")
    if sf and not sf["fits"]:
        if sf["collides_grid"]:
            add("fail", "subtitle",
                f"subtitle wraps to {sf['lines']} lines and intrudes into the grid reserve; "
                "shorten the subtitle")
        else:
            add("fail", "subtitle",
                f"subtitle does not fit the content width within {sf['max_lines']} lines even at "
                f"the minimum size ({sf['lines']} lines, {sf['overflow_px']:.0f}px over); "
                "shorten the subtitle")
    elif sf and (sf["lines"] > 1 or sf["shrunk_to"]):
        how = []
        if sf["lines"] > 1:
            how.append(f"wrapped to {sf['lines']} lines")
        if sf["shrunk_to"]:
            how.append(f"shrunk to {sf['shrunk_to']:.4f}H (configured {cfg['size_subtitle']:.4f}H)")
        add("warn", "subtitle",
            "subtitle " + " and ".join(how) + " to fit; fine to ship, but a shorter "
            "subtitle would sit on one line at full size")
    if ctx.get("clues_fit") is False:
        add("fail", "clues", "clues do not fit the two columns at the minimum size")
    sep = ctx.get("separator")
    if sep and ctx.get("grid_bottom_px") and ctx["grid_bottom_px"] > sep[2] + 1:
        add("fail", "grid", "grid overruns the separator rule")
    for ci in (0, 1):
        foot = ctx.get(f"clue_foot_{ci}")
        if foot and foot > cfg["clue_bottom"] * ctx["H"] + 1:
            add("fail", "clues", f"column {ci} clues overflow past the clue-zone bottom")
    return out


def print_report(diags, label):
    fails = [d for d in diags if d[0] == "fail"]
    warns = [d for d in diags if d[0] == "warn"]
    tag = {"fail": "FAIL", "warn": "WARN", "info": "INFO"}
    print(f"\n=== Pre-render check: {label} ===")
    if not diags:
        print("  (no issues)")
    for lvl, field, msg in diags:
        print(f"  [{tag[lvl]}] {field}: {msg}")
    ok = not fails
    print("  " + "-" * 40)
    print(f"  {'PASS' if ok else 'FAIL'} — {len(fails)} failure(s), {len(warns)} warning(s)")
    return ok


# ---------------------------------------------------------------------------
# Driver.
# ---------------------------------------------------------------------------


def build(template_path, data_path, output_path, cfg=CONFIG,
          print_dpi=None, print_size=None, render_dpi=None, render_size=None,
          ink_blur=None, bleed_mm=0.0, crop_marks=False, seed=None):
    with open(data_path, "r", encoding="utf-8") as fh:
        data = json.load(fh)

    # Generate the grid (or accept a pre-built one in the data file).
    if data.get("grid_data"):
        gridres = data["grid_data"]
    else:
        eff_seed = seed if seed is not None else data.get("seed")
        gridres = grid_generator.generate_grid(
            data["candidates"],
            min_words=data.get("min_words", cfg["min_words"]),
            max_words=data.get("max_words", cfg["max_words"]),
            seed=eff_seed, attempts=cfg["grid_attempts"],
            anchors=data.get("anchors"))
    print(f"[info] grid: {gridres['word_count']} words on {gridres['rows']}x{gridres['cols']} "
          f"({len(gridres['across'])} across, {len(gridres['down'])} down)")
    if gridres.get("anchors"):
        placed_anchors = [a for a in gridres["anchors"] if a not in gridres["anchors_missing"]]
        print(f"[info] anchors: {len(placed_anchors)}/{len(gridres['anchors'])} placed"
              + (f"; MISSING: {', '.join(gridres['anchors_missing'])}" if gridres["anchors_missing"] else ""))

    template = Image.open(template_path).convert("RGB")
    print(f"[info] template {os.path.basename(template_path)}: {template.width}x{template.height}px")

    if render_size or render_dpi:
        if render_size:
            tw, th = render_size
        else:
            mm = cfg["a2_mm"]
            tw = int(round(mm[0] / 25.4 * render_dpi))
            th = int(round(mm[1] / 25.4 * render_dpi))
        if (tw, th) != template.size:
            print(f"[info] upscaling template {template.width}x{template.height} -> {tw}x{th} "
                  f"before rendering" + (f" ({render_dpi} DPI)" if render_dpi else ""))
            template = template.resize((tw, th), Image.LANCZOS)
    W, H = template.size

    # Two cairo surfaces: ink text (multiplied into paper) and the grid (white
    # cells composited on top of the paper).
    ink_surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, W, H)
    ink_cr = cairo.Context(ink_surface)
    assert_fonts_resolved(ink_cr, cfg)
    grid_surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, W, H)
    grid_cr = cairo.Context(grid_surface)

    ctx = {"W": W, "H": H, "cfg": cfg}
    cell, ox, oy = compute_grid_geometry(ctx, gridres)
    ctx["cell"], ctx["grid_ox"], ctx["grid_oy"] = cell, ox, oy
    print(f"[info] grid cell {cell:.1f}px ({cell/H:.4f}H), grid block "
          f"{cell*gridres['cols']:.0f}x{cell*gridres['rows']:.0f}px")

    render_title(ink_cr, ctx, data)
    render_grid(grid_cr, ctx, gridres)
    render_clues(ink_cr, ctx, gridres)
    render_credit(ink_cr, ctx, data)

    ink_rgba = cairo_to_pil(ink_surface)
    result = composite_ink(template, ink_rgba, cfg, W, ink_blur=ink_blur)
    result = draw_separator(result, ctx)
    # Composite the grid (warm-white cells, dark borders, numbers) over the paper.
    grid_rgba = cairo_to_pil(grid_surface)
    result = result.convert("RGBA")
    result.alpha_composite(grid_rgba)
    result = result.convert("RGB")

    result, dpi = finalize_output(result, cfg, print_dpi, print_size)
    if bleed_mm > 0 or crop_marks:
        result = add_bleed_and_marks(result, cfg, bleed_mm, crop_marks)

    diagnostics = run_checks(ctx, gridres, cfg)
    fails = [d for d in diagnostics if d[0] == "fail"]
    if output_path is not None:
        save_kwargs = {"icc_profile": srgb_icc_bytes()}
        if dpi:
            save_kwargs["dpi"] = (dpi, dpi)
        if fails:
            root, ext = os.path.splitext(output_path)
            quarantine = root + ".FAILED" + ext
            result.save(quarantine, **save_kwargs)
            print(f"[error] {len(fails)} layout failure(s); deliverable WITHHELD:")
            for _lvl, field, msg in fails:
                print(f"[error]   {field}: {msg}")
            print(f"[error] wrote quarantined render to {quarantine} (NOT print-ready).")
        else:
            result.save(output_path, **save_kwargs)
            print(f"[done] wrote {output_path} ({result.width}x{result.height}px)")
    return diagnostics


def main():
    ap = argparse.ArgumentParser(description="Render a company crossword onto a blank template.")
    ap.add_argument("--template", required=True)
    ap.add_argument("--data", required=True)
    ap.add_argument("--output", default=None, help="output PNG path (optional with --check)")
    ap.add_argument("--check", action="store_true", help="validate and print a PASS/FAIL report")
    ap.add_argument("--print-dpi", type=int, default=None,
                    help="downsample the finished page to A2 at this DPI and tag the PNG")
    ap.add_argument("--print-size", default=None, help="explicit WIDTHxHEIGHT, overrides --print-dpi")
    ap.add_argument("--render-dpi", type=int, default=None,
                    help="upscale the template to A2 at this DPI BEFORE rendering")
    ap.add_argument("--render-size", default=None, help="explicit WIDTHxHEIGHT to upscale to")
    ap.add_argument("--seed", type=int, default=None, help="grid generation seed (reproducible)")
    ap.add_argument("--ink-blur", type=float, default=None,
                    help="ink-spread blur in px on the text (0 = razor sharp)")
    ap.add_argument("--bleed-mm", type=float, default=0.0, help="bleed (mm) on every side")
    ap.add_argument("--crop-marks", action="store_true", help="draw crop marks in the bleed margin")
    args = ap.parse_args()

    def parse_size(s):
        if not s:
            return None
        w, h = s.lower().split("x")
        return (int(w), int(h))

    if not args.check and not args.output:
        ap.error("--output is required unless --check is given")

    render_dpi = args.render_dpi
    render_size = parse_size(args.render_size)
    # No render-dpi default for --check: the gate lays out at the native
    # template raster, exactly as the production render does (see the
    # newspaper engine for the rationale).

    diagnostics = build(
        args.template, args.data, args.output,
        print_dpi=args.print_dpi, print_size=parse_size(args.print_size),
        render_dpi=render_dpi, render_size=render_size, ink_blur=args.ink_blur,
        bleed_mm=args.bleed_mm, crop_marks=args.crop_marks, seed=args.seed)

    if args.check:
        ok = print_report(diagnostics, os.path.basename(args.data))
        sys.exit(0 if ok else 1)
    if any(d[0] == "fail" for d in diagnostics):
        sys.exit(1)


if __name__ == "__main__":
    main()
